### ISSUE TITLE
Add idmtools-test nightly or version dist to github actions

### ISSUE THREAD

**Issue by shchen-idmod** [InstituteforDiseaseModeling/idmtools#816]
With code in each staging-idmtools-xxx.yml, we can add these few lines to bottom of file to upload dist to github actions's artifact:
see here:
https://github.com/shchen-idmod/idmtools/actions/runs/95653768

```
      - name: Upload idmtools-test package to github artifactory
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: idmtools_test package
          path: idmtools_test/dist/
```
This will upload a zip file from 'dist' folder with whl and tar.gz files to github actions. i.e:
idmtools_test-1.0.1+nightly.tar.gz
idmtools_test-1.0.1+nightly-py3-none-any.whl

User can simply download from Actions tab and unzip it then do pip install from local whl or gz file
